### PR TITLE
Adding * as a selector option

### PR DESCRIPTION
**Pull request by sduskis**
Issue #221 seems popular.  A handful of users want something that will include all children at a particular level.  This pull request should satisfy that request.

### CODE REVIEW

**Comment by kentongray** [comment]
this looks like a great change (especially for hashmaps), curious about the use of underscore on var naming?

**Comment by sduskis** [comment]
That's a customization that we can add if there's popular demand for it.  The \* changes can be used as an example for further extension, if you so desire.

**Comment by cepage** [comment]
Thanks for keeping the dream alive, Solomon! Looks great.

**Comment by cabbonizio** [comment]
Looking forward to using this.  Curious if this also addresses another request I inquired about...if no selector is specifies then return all fields.  I know the \* was designed for returning all fields at specific levels.  This would be useful for those transitioning clients to using selectors on existing services since they wouldn't be sending a selector initially.  Thanks

**Comment by kentongray** [comment]
You might just look at adding a filter to add a default selector param or
hook into yoga. I personally hope this doesn't become a default or at least
it is configurable.

**Comment by cabbonizio** [comment]
Hi, I updated the dependencies to 1.0.5 and tried the use of the "*".   It doesn't seem to be working for me.   

As an example, I had a selector like this before that worked well (still works after 1.0.5 upgrade):

selector=showLine(showCode,sourceSeqNbr)

I tried the selector below and the response did not return any fields under the showLine object:
selector=showLine(*)

Am I using this incorrectly????

**Comment by safder-meah** [comment]
I was able to use the "*" selector by extending JSonSelectorView and turning on setStarResolvesToAll and it definitely outputs all the fields in a specific level, however ideally, i would want a way to get all the fields as mentioned by @cabbonizio . I didn't follow what @kentongray meant by "adding a filter". Are you referring to the Jackson 2 filters?

**Pull request merged**
