### PR TITLE
Redone to double-checked locking idiom

### PR DESCRIPTION
**Pull request by shlasouski**

### CODE REVIEW

**Comment by sduskis** [comment]
It would probably be better to simply do the logic in a constructor...

**Comment by carterpage** [comment]
This approach is, in general, a little problematic in Java.  (see http://en.wikipedia.org/wiki/Double-checked_locking)

I think Solomon's suggestion is the best.  It's a safe-enough operation to implement it in the constructor, and that will take care of thread-safety.  Only thing I can think of is if the reflection is expensive relative to object construction, but I don't believe that's an issue with modern JVM's.

**Comment by carterpage** [comment]
Actually I take back my objection.  SInce the _instanceClass is volatile, this is safe in JDK 1.5 and after.

**Comment by sduskis** [comment]
This is a configuration class that's used only at startup.  There's every reason to keep this class simple and clean of any threading logic.

**Comment by shlasouski** [comment]
Thanks, I understood. I thought that it's multithreading class due to volatile field.

**Pull request closed without merging**
