### PR TITLE
Added null check to type discovery in MetaDataRegistry

### PR DESCRIPTION
**Pull request by cepage**

### CODE REVIEW

**Comment by sduskis** [comment]
Was there some error condition that triggered this change?  If so, we probably should cover that case

**Comment by cepage** [comment]
Yes, if the readMethod returns an untyped iterable:

public List getCustomers()

then _getCollectionType_ returns null, and the _addFields_ method crashes.

**Comment by sduskis** [comment]
So shouldn't we be handling that case by producing something (tbd) instead of nothing?

**Comment by cepage** [comment]
Yes, let's discuss during call

**Pull request merged**
